name: Terraform
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy


env:
  TF_VERSION: '1.14.6'
  YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
  YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  YC_TOKEN: ${{ secrets.YC_TOKEN }}

jobs:
  terraform:
    outputs:
      vm_ip: ${{ steps.vm_ip.outputs.IP }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
        
    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
      run: |
        cd infrastructure/vm
        terraform init
      
    - name: Terraform Plan
      if: inputs.action == 'plan'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
      run: |
        cd infrastructure/vm
        terraform plan -var="cloud_id=${{ env.YC_CLOUD_ID }}" -var="folder_id=${{ env.YC_FOLDER_ID }}" -var="token=${{ env.YC_TOKEN }}"
      
    - name: Terraform Apply
      if: inputs.action == 'apply'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
      run: |
        cd infrastructure/vm
        terraform apply -auto-approve -var="cloud_id=${{ env.YC_CLOUD_ID }}" -var="folder_id=${{ env.YC_FOLDER_ID }}" -var="token=${{ env.YC_TOKEN }}"
        
    - name: Extract VM IP
      id: vm_ip
      if: inputs.action == 'apply'
      run: |
        cd infrastructure/vm
        IP=$(terraform output -raw ip_address)
        echo "IP=$IP" >> $GITHUB_OUTPUT
        echo "VM IP = $IP"

    - name: Trigger Deploy Workflow
      if: inputs.action == 'apply'
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.PAT }}
        event-type: deploy
        client-payload: |
          {
            "vm_ip": "${{ steps.vm_ip.outputs.IP }}",
            "sha": "${{ github.sha }}",
            "ref": "${{ github.ref }}"
          }
    
    - name: Terraform Destroy
      if: inputs.action == 'destroy'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
      run: |
        cd infrastructure/vm
        terraform destroy -auto-approve -var="cloud_id=${{ env.YC_CLOUD_ID }}" -var="folder_id=${{ env.YC_FOLDER_ID }}" -var="token=${{ env.YC_TOKEN }}"
