name: Terraform
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy

env:
  TF_VERSION: '1.14.6'
  YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
  YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  YC_TOKEN: ${{ secrets.YC_TOKEN }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
        
    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
      run: |
        cd infrastructure/vm
        terraform init
      
    - name: Terraform Plan
      if: inputs.action == 'plan'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
        YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}     
        YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}  
        YC_TOKEN: ${{ secrets.YC_TOKEN }}
      run: |
        cd infrastructure/vm
        terraform plan
      
    - name: Terraform Apply
      if: inputs.action == 'apply'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
        YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}     
        YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}  
        YC_TOKEN: ${{ secrets.YC_TOKEN }}
      run: |
        cd infrastructure/vm
        terraform apply -auto-approve
        
    - name: Extract VM IP
      id: vm_ip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
        YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}     
        YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}  
        YC_TOKEN: ${{ secrets.YC_TOKEN }}
      if: inputs.action == 'apply'
      run: |
        cd infrastructure/vm
        IP=$(terraform output -raw ip_address)
        echo $IP > ./vm_ip.txt

    - name: Upload VM IP Artifact
      if: inputs.action == 'apply'
      uses: actions/upload-artifact@v4
      with:
        name: vm-ip
        path: ./vm_ip.txt
    
    - name: Terraform Destroy
      if: inputs.action == 'destroy'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-central1
        YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}     
        YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}  
        YC_TOKEN: ${{ secrets.YC_TOKEN }}
      run: |
        cd infrastructure/vm
        terraform destroy -auto-approve
